# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(400, 300)

        self.invalid=QtGui.QIntValidator()# کاربر فقط عدد وارد کنه

        self.verticalLayout = QtWidgets.QVBoxLayout(widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input1 = QtWidgets.QLineEdit(parent=widget)
        self.input1.setObjectName("input1")
        self.verticalLayout.addWidget(self.input1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sub = QtWidgets.QPushButton(parent=widget)
        self.sub.setObjectName("sub")
        self.horizontalLayout.addWidget(self.sub)
        self.input3 = QtWidgets.QLineEdit(parent=widget)
        self.input3.setObjectName("input3")
        self.horizontalLayout.addWidget(self.input3)
        self.plus = QtWidgets.QPushButton(parent=widget)
        self.plus.setObjectName("plus")
        self.horizontalLayout.addWidget(self.plus)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.input2 = QtWidgets.QLineEdit(parent=widget)
        self.input2.setObjectName("input2")
        self.verticalLayout.addWidget(self.input2)

        self.plus.clicked.connect(self.plus_func)
        self.sub.clicked.connect(self.sub_func)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "calculator"))
        self.input1.setPlaceholderText(_translate("widget", "input1"))
        self.sub.setText(_translate("widget", "-"))
        self.input3.setPlaceholderText(_translate("widget", "output"))
        self.plus.setText(_translate("widget", "+"))
        self.input2.setPlaceholderText(_translate("widget", "input2"))

    def plus_func(self):
        data_1 = int(self.input1.text())
        data_2 = int(self.input2.text())   
        self.input3.setText(f"{data_1+data_2}")

    def sub_func(self):
        data_1 = int(self.input1.text())
        data_2 = int(self.input2.text())   
        self.input3.setText(f"{data_1-data_2}")   


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_widget()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec())
